# data folder
data_folder: data

# saves
saves_folder: saves

# data files

# fonts
fonts_h: font.h
fonts_training: fonts_training.json

# plotting
plotting: True

# multilayer config
momentum: False
momentum_mult: 0.8
progress_bar: True

# vae config
images_folder: developer-faces
images_shape:
  width: 16
  height: 16