# data folder
data_folder: data

# saves
saves_folder: saves

# data files

# fonts
fonts_h: font.h
fonts_training: fonts_training.json

# plotting
plotting: True

# multilayer config
progress_bar: True

# vae config
images_folder: minecraft-faces
images_shape:
  width: 16
  height: 16